# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NJCCData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nj_cc_data_tables',
            name='credits',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='nj_cc_data_tables',
            name='equivalent_course',
            field=models.FileField(upload_to=''),
        ),
    ]
