# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NJCCData', '0002_auto_20170629_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nj_cc_data_tables',
            name='credits',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nj_cc_data_tables',
            name='equivalent_course',
            field=models.CharField(max_length=50),
        ),
    ]
